;;; dianyou-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dianyou.el

(autoload 'dianyou-group-make-nnir-group "dianyou" "\
Search emails like `gnus-group-make-nnir-group'.
Prompt for search query and determine groups to search as follows:
In *Server* buffer, search all groups belonging to current server;
In *Group* buffer, search marked groups, or the current group,
or all the groups under the current topic;
In *Summary* buffer, search the group current buffer belonging to.

IMAP search syntax supports shortcut and more date format:
\"t\" equals \"TO\".
\"b\" equals \"BEFORE\".
\"e\" equals \"TEXT\".
\"u\" equals \"SUBJECT\".
\"o\" equals \"OR\".
\"c\" equals \"CC\".
\"f\" equals \"FROM\".
\"s\" equals \"SINCE\".
\"20180905\" or \"180905\" equals \"5-Sep-2018\".
\"2018-09-05\" or \"18-09-05\" equals \"5-Sep-2018\".
\"1y1m1w1d\" equals the date 1 year 1 month 1 week 1 day ago.
See https://tools.ietf.org/html/rfc3501#section-6.4.4 for IMAP SEARCH spec." t)
(autoload 'dianyou-all-email-address "dianyou" "\
Return all email address extracted from received mails.
Email address matching EXCLUDE-REGEXP is excluded from final result.

(fn &optional EXCLUDE-REGEXP)")
(autoload 'dianyou-summary-extract-email-address "dianyou" "\
Extract email address from email to/cc/from field in *Summary* buffer.
REGEXP is pattern to exclude email address.
For example, 'Tom|gmail' excludes address containing \"Tom\" or \"gmail\".
Final result is inserted into `kill-ring' and returned.

(fn REGEXP)" t)
(autoload 'dianyou-get-all-email-addresses "dianyou" "\
Get all email addresses in received mails and update history.")
(autoload 'dianyou-insert-email-address-from-received-mails "dianyou" "\
Insert email address from received mails." t)
(autoload 'dianyou-switch-gnus-buffer "dianyou" "\
Switch between Gnus buffers." t)
(autoload 'dianyou-paste-image-from-clipboard "dianyou" "\
Paste image from clipboard.  CLI program xclip is required." t)
(autoload 'dianyou-email-view-in-browser "dianyou" "\
View the body of email in browser.
You can influence the browser to use with the variable `browse-url-generic-program'." t)
(register-definition-prefixes "dianyou" '("dianyou-"))

;;; End of scraped data

(provide 'dianyou-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dianyou-autoloads.el ends here
